"""Chinese presentation metadata for the public research-skill catalog.

Slugs remain stable installation identifiers. These labels are deliberately
kept outside SKILL.md so localization never changes the installable manifest.
"""

from __future__ import annotations


SKILL_NAMES_ZH = {
    "announcement-search": "公告搜索",
    "adr-hshare": "美股存托凭证、港股与A股价差分析",
    "akshare": "AKShare金融数据获取",
    "alpha-zoo": "量化因子库研究",
    "ashare-pre-st-filter": "A股ST风险预警筛选",
    "asset-allocation": "资产配置与组合优化",
    "backtest-diagnose": "回测问题诊断",
    "behavioral-finance": "行为金融分析",
    "candlestick": "K线形态识别",
    "ccxt": "CCXT数字资产行情获取",
    "chanlun": "缠论形态分析",
    "commodity-analysis": "大宗商品研究",
    "convertible-bond": "A股可转债分析",
    "corporate-events": "公司事件与行动分析",
    "correlation-analysis": "相关性与协整分析",
    "credit-analysis": "信用与债券风险分析",
    "cross-market-strategy": "跨市场策略研究",
    "crypto-derivatives": "数字资产衍生品策略",
    "data-routing": "金融数据源智能选择",
    "defi-yield": "去中心化金融收益分析",
    "dividend-analysis": "股息质量与分红持续性分析",
    "doc-reader": "投研文档读取",
    "earnings-forecast": "盈利预测与一致预期分析",
    "earnings-revision": "盈利预测修正分析",
    "edgar-sec-filings": "美国上市公司公告分析",
    "elliott-wave": "艾略特波浪分析",
    "etf-analysis": "ETF产品分析与筛选",
    "event-driven": "事件驱动策略研究",
    "execution-model": "交易执行成本建模",
    "factor-research": "量化因子研究",
    "financial-statement": "财务报表分析",
    "fund-analysis": "基金分析与筛选",
    "fundamental-filter": "基本面因子筛选",
    "geopolitical-risk": "地缘政治风险分析",
    "global-macro": "全球宏观研究",
    "harmonic": "谐波形态分析",
    "hithink-astock-selector": "问财选A股",
    "hithink-basicinfo-query": "公司基本资料查询",
    "hithink-business-query": "公司经营数据查询",
    "hithink-cb-selector": "问财选可转债",
    "hithink-etf-selector": "问财选ETF",
    "hithink-event-query": "事件数据查询",
    "hithink-finance-query": "财务数据查询",
    "hithink-fund-query": "基金理财查询",
    "hithink-fund-selector": "问财选基金",
    "hithink-fundcompany-selector": "问财选基金公司",
    "hithink-fundmanager-selector": "问财选基金经理",
    "hithink-futures-query": "期货期权数据查询",
    "hithink-futures-selector": "问财选期货期权",
    "hithink-hkstock-selector": "问财选港股",
    "hithink-industry-query": "行业数据查询",
    "hithink-insresearch-query": "机构研究与评级查询",
    "hithink-macro-query": "宏观数据查询",
    "hithink-management-query": "公司股东股本查询",
    "hithink-market-query": "行情数据查询",
    "hithink-sector-selector": "问财选板块",
    "hithink-usstock-selector": "问财选美股",
    "hithink-zhishu-query": "指数数据查询",
    "hedging-strategy": "投资组合对冲策略",
    "hk-connect-flow": "沪深港通资金流分析",
    "ichimoku": "一目均衡表分析",
    "liquidation-heatmap": "数字资产清算热力图分析",
    "macro-analysis": "宏观经济周期分析",
    "market-microstructure": "市场微观结构分析",
    "minute-analysis": "分钟行情分析与回测",
    "ml-strategy": "机器学习预测策略",
    "mootdx": "通达信行情数据获取",
    "multi-factor": "多因子选股与排序",
    "news-search": "新闻搜索",
    "okx-market": "OKX数字资产行情获取",
    "onchain-analysis": "区块链链上数据分析",
    "options-advanced": "高级期权策略",
    "options-payoff": "期权损益与情景分析",
    "options-strategy": "期权组合策略研究",
    "pair-trading": "配对交易策略",
    "performance-attribution": "投资业绩归因分析",
    "perp-funding-basis": "永续合约资金费率与基差策略",
    "pine-script": "交易策略脚本导出",
    "quant-statistics": "量化统计方法",
    "regulatory-knowledge": "金融市场监管知识",
    "report-search": "研报搜索",
    "report-generate": "专业投研报告生成",
    "research-goal": "目标驱动投研流程",
    "risk-analysis": "风险度量与压力测试",
    "seasonal": "季节性与日历效应策略",
    "sector-rotation": "行业轮动策略",
    "sentiment-analysis": "市场情绪分析",
    "shadow-account": "影子账户行为分析",
    "smc": "机构资金行为与结构分析",
    "social-media-intelligence": "社交媒体金融情报分析",
    "stablecoin-flow": "稳定币资金流分析",
    "strategy-generate": "量化策略生成与优化",
    "technical-basic": "基础技术指标分析",
    "token-unlock-treasury": "代币解锁与项目金库分析",
    "trade-journal": "交易日志复盘分析",
    "tushare": "Tushare金融数据研究",
    "us-etf-flow": "美国ETF资金流与行业广度分析",
    "valuation-model": "公司估值模型",
    "vnpy-export": "交易策略导出至vn.py",
    "volatility": "波动率策略研究",
    "web-reader": "投研网页读取",
    "yfinance": "雅虎财经数据获取",
}


def localized_skill_metadata(slug: str, fallback_name: str, fallback_description: str) -> tuple[str, str]:
    name = SKILL_NAMES_ZH.get(slug)
    if name is None:
        name = f"专业投研分析（{fallback_name}）"
    description = f"围绕{name}提供数据获取、指标解读、分析步骤、结果验证与风险提示，供本地AI智能体直接执行。"
    return name, description
