import { useEffect, useState } from "react";
import { LoaderCircle, RefreshCw } from "lucide-react";
import { authHeaders } from "@/lib/apiAuth";

interface ModuleData { module: string; title: string; description: string; columns: string[]; stats: { key: string; label: string; value: number | string | null }[]; rows: { id: string; cells: string[] }[]; as_of: string }

export function AdminModulePage({ module }: { module: "users" | "dataHub" | "content" | "audit" | "system" }) {
  const [data, setData] = useState<ModuleData | null>(null); const [error, setError] = useState(""); const [revision, setRevision] = useState(0);
  useEffect(() => { setData(null); setError(""); fetch(`/api/admin/modules/${module}`, { headers: authHeaders() }).then(async response => { if (!response.ok) throw new Error((await response.json()).detail || `HTTP ${response.status}`); return response.json() as Promise<ModuleData>; }).then(setData).catch(cause => setError(cause instanceof Error ? cause.message : "加载失败")); }, [module, revision]);
  if (error) return <div className="mx-auto max-w-6xl p-8"><h1 className="text-xl font-semibold">运营数据加载失败</h1><p className="mt-2 text-sm text-red-600">{error}</p><button onClick={() => setRevision(value => value + 1)} className="mt-4 rounded-md border px-3 py-2 text-sm">重试</button></div>;
  if (!data) return <div className="flex items-center justify-center gap-2 p-20 text-sm text-muted-foreground"><LoaderCircle className="h-5 w-5 animate-spin"/>读取真实运营数据</div>;
  return <div className="mx-auto max-w-6xl space-y-6 p-8"><header className="flex items-end justify-between"><div><p className="text-xs font-medium uppercase tracking-[.16em] text-primary">Operations</p><h1 className="mt-1 text-2xl font-semibold">{data.title}</h1><p className="mt-1 text-sm text-muted-foreground">{data.description}</p></div><button onClick={() => setRevision(value => value + 1)} className="inline-flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><RefreshCw className="h-4 w-4"/>刷新</button></header><section className="grid gap-3 sm:grid-cols-3">{data.stats.map(item => <div key={item.key} className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">{item.label}</p><p className="mt-2 text-2xl font-semibold">{item.value ?? "暂无数据"}</p></div>)}</section><section className="overflow-hidden rounded-xl border bg-card"><div className="flex justify-between border-b px-4 py-3"><h2 className="text-sm font-semibold">最近记录</h2><span className="text-xs text-muted-foreground">更新于 {new Date(data.as_of).toLocaleString()}</span></div>{data.rows.length === 0 ? <div className="p-12 text-center text-sm text-muted-foreground">当前服务没有可展示的记录</div> : <><div className="grid gap-2 bg-muted/40 px-4 py-2 text-xs font-medium" style={{ gridTemplateColumns: `repeat(${data.columns.length}, minmax(0, 1fr))` }}>{data.columns.map(column => <span key={column}>{column}</span>)}</div><div className="divide-y">{data.rows.map(row => <div key={row.id} className="grid gap-2 px-4 py-3 text-sm" style={{ gridTemplateColumns: `repeat(${row.cells.length}, minmax(0, 1fr))` }}>{row.cells.map((cell, index) => <span key={index} className={index ? "text-muted-foreground" : "font-medium"}>{cell}</span>)}</div>)}</div></>}</section></div>;
}
