import { useEffect, useState } from "react";
import { Bot, Database, KeyRound, RefreshCw, Save, ShieldCheck } from "lucide-react";
import { authHeaders } from "@/lib/apiAuth";

type Provider = { code: string; name: string; default_model: string; default_base_url: string; api_key_required?: boolean; auth_type?: string; login_command?: string | null };
type Settings = { provider: string; model_name: string; base_url: string; api_key_configured: boolean; temperature: number; timeout_seconds: number; max_retries: number; reasoning_effort: string; providers: Provider[] };
type Credentials = { tushare_token_configured: boolean; tpdog_token_configured: boolean; blackwolf_token_configured: boolean };
const empty: Settings = { provider: "", model_name: "", base_url: "", api_key_configured: false, temperature: .2, timeout_seconds: 90, max_retries: 2, reasoning_effort: "", providers: [] };

async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, { ...init, headers: { ...(init?.body ? { "Content-Type": "application/json" } : {}), ...authHeaders(), ...init?.headers } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || `平台配置请求失败（${response.status}）`); return body as T; }

export function AISettingsPage() {
  const [form, setForm] = useState<Settings>(empty); const [credentials, setCredentials] = useState<Credentials>({ tushare_token_configured: false, tpdog_token_configured: false, blackwolf_token_configured: false }); const [apiKey, setApiKey] = useState(""); const [tushare, setTushare] = useState(""); const [tpdog, setTpdog] = useState(""); const [blackwolf, setBlackwolf] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const [settings, sources] = await Promise.all([request<Settings>("/api/admin/ai/settings"), request<Credentials>("/api/admin/ai/source-credentials")]); setForm({ ...empty, ...settings }); setCredentials(sources); } catch (e) { setError(e instanceof Error ? e.message : "加载失败"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const selectProvider = (code: string) => { const item = form.providers.find(p => p.code === code); setForm({ ...form, provider: code, model_name: item?.default_model ?? "", base_url: item?.default_base_url ?? "", api_key_configured: false }); };
  const save = async () => { try { const provider = form.providers.find(p => p.code === form.provider); if (apiKey) await request(`/api/admin/ai/providers/${form.provider}`, { method: "PUT", body: JSON.stringify({ name: provider?.name ?? form.provider, base_url: form.base_url, api_key: apiKey, models: [form.model_name], enabled: true }) }); await request("/api/admin/ai/settings", { method: "PUT", body: JSON.stringify({ provider: form.provider, model_name: form.model_name, base_url: form.base_url, temperature: form.temperature, timeout_seconds: form.timeout_seconds, max_retries: form.max_retries, reasoning_effort: form.reasoning_effort }) }); setApiKey(""); setMessage("平台 AI 配置已保存，AI 发现的新任务将使用该模型"); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "保存失败"); } };
  const saveSources = async () => { try { const value = await request<Credentials>("/api/admin/ai/source-credentials", { method: "PUT", body: JSON.stringify({ tushare_token: tushare || undefined, tpdog_token: tpdog || undefined, blackwolf_token: blackwolf || undefined }) }); setCredentials(value); setTushare(""); setTpdog(""); setBlackwolf(""); setMessage("数据源凭据已加密保存"); } catch (e) { setMessage(e instanceof Error ? e.message : "保存失败"); } };
  if (loading) return <div className="p-20 text-center text-sm text-muted-foreground">正在加载平台配置…</div>;
  if (error) return <div className="mx-auto max-w-6xl p-8"><div className="rounded-xl border border-red-200 bg-red-50 p-8 text-center text-red-700">{error}<br/><button className="mt-4 rounded-md border bg-white px-3 py-2" onClick={() => void load()}>重新加载</button></div></div>;
  return <div className="mx-auto max-w-6xl space-y-6 p-8"><header className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">AI Research Runtime</p><h1 className="mt-1 text-2xl font-semibold">AI 投研配置</h1><p className="mt-2 text-sm text-muted-foreground">配置 Web 端 AI 发现统一使用的模型和研究数据源；客户端本地配置不受影响。</p></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><RefreshCw className="h-4 w-4"/>刷新</button></header>{message && <div className="rounded-lg border bg-card px-4 py-3 text-sm">{message}</div>}
    <section className="rounded-xl border bg-card p-6"><Title icon={Bot} title="平台模型" detail="选择一个默认模型，AI 发现的理解、分析和报告统一由它完成。"/><div className="mt-5 grid gap-4 md:grid-cols-2"><Select label="模型供应商" value={form.provider} onChange={selectProvider} options={form.providers.map(p => [p.code, p.name])}/><Field label="模型 ID" value={form.model_name} onChange={model_name => setForm({ ...form, model_name })}/><Field label="服务地址" value={form.base_url} onChange={base_url => setForm({ ...form, base_url })}/><Field label="API Key" secret value={apiKey} onChange={setApiKey} hint={form.api_key_configured ? "已配置，留空不会覆盖" : "尚未配置"}/></div><div className="mt-7 border-t pt-6"><h3 className="font-medium">生成参数</h3><div className="mt-4 grid gap-4 md:grid-cols-4"><NumberField label="温度" value={form.temperature} onChange={temperature => setForm({ ...form, temperature })}/><NumberField label="超时（秒）" value={form.timeout_seconds} onChange={timeout_seconds => setForm({ ...form, timeout_seconds })}/><NumberField label="失败重试" value={form.max_retries} onChange={max_retries => setForm({ ...form, max_retries })}/><Select label="推理强度" value={form.reasoning_effort} onChange={reasoning_effort => setForm({ ...form, reasoning_effort })} options={[["", "模型默认"], ["low", "低"], ["medium", "中"], ["high", "高"], ["max", "最高"]]}/></div></div><button disabled={!form.provider || !form.model_name || !form.base_url} onClick={() => void save()} className="mt-6 inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50"><Save className="h-4 w-4"/>保存平台 AI 配置</button></section>
    <section className="rounded-xl border bg-card p-6"><Title icon={Database} title="数据源凭据" detail="Data Hub 是平台主数据源；以下凭据用于补充覆盖和故障降级。"/><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="黑狼数据 Token" secret value={blackwolf} onChange={setBlackwolf} hint={credentials.blackwolf_token_configured ? "已配置，留空不会覆盖" : "未配置"}/><Field label="Tushare Token" secret value={tushare} onChange={setTushare} hint={credentials.tushare_token_configured ? "已配置，留空不会覆盖" : "未配置"}/><Field label="TPDog Token" secret value={tpdog} onChange={setTpdog} hint={credentials.tpdog_token_configured ? "已配置，留空不会覆盖" : "未配置"}/></div><div className="mt-5 flex items-center justify-between rounded-lg bg-muted/40 p-4"><div className="flex items-center gap-2 text-sm"><ShieldCheck className="h-4 w-4 text-emerald-600"/>凭据仅在服务端加密保存，不返回明文</div><button onClick={() => void saveSources()} disabled={!tushare && !tpdog && !blackwolf} className="rounded-md border bg-background px-4 py-2 text-sm disabled:opacity-50">保存数据源凭据</button></div></section></div>;
}
function Title({ icon: Icon, title, detail }: { icon: typeof Bot; title: string; detail: string }) { return <div className="flex items-center gap-3"><Icon className="h-5 w-5 text-primary"/><div><h2 className="font-semibold">{title}</h2><p className="text-xs text-muted-foreground">{detail}</p></div></div>; }
function Field({ label, value, onChange, secret, hint }: { label: string; value: string; onChange: (v: string) => void; secret?: boolean; hint?: string }) { return <label className="text-xs text-muted-foreground">{label}<div className="relative mt-1">{secret && <KeyRound className="absolute left-3 top-3 h-4 w-4"/>}<input type={secret ? "password" : "text"} value={value} onChange={e => onChange(e.target.value)} className={`h-10 w-full rounded-md border bg-background px-3 text-sm ${secret ? "pl-9" : ""}`}/></div>{hint && <span className="mt-1 block">{hint}</span>}</label>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (v: number) => void }) { return <label className="text-xs text-muted-foreground">{label}<input type="number" value={value} onChange={e => onChange(Number(e.target.value))} className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm"/></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (v: string) => void; options: string[][] }) { return <label className="text-xs text-muted-foreground">{label}<select aria-label={label} value={value} onChange={e => onChange(e.target.value)} className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm">{options.map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label>; }
