import { useEffect, useState } from "react";
import { Bot, KeyRound, Save } from "lucide-react";
import { authHeaders } from "@/lib/apiAuth";

type Provider = { code: string; name: string; base_url: string; models: string[]; enabled: boolean; api_key_masked: string | null; configured: boolean };

export function AISettingsPage() {
  const [providers, setProviders] = useState<Provider[]>([]);
  const [code, setCode] = useState("openai"); const [name, setName] = useState("OpenAI");
  const [baseUrl, setBaseUrl] = useState("https://api.openai.com/v1"); const [apiKey, setApiKey] = useState("");
  const [models, setModels] = useState("gpt-5.2"); const [message, setMessage] = useState("");
  const [temperature, setTemperature] = useState("0.2"); const [timeout, setTimeoutValue] = useState("90");
  const load = () => fetch("/api/admin/ai/providers", { headers: authHeaders() }).then(r => r.json()).then(setProviders);
  useEffect(() => { void load(); }, []);
  const save = async () => {
    setMessage("");
    const response = await fetch(`/api/admin/ai/providers/${encodeURIComponent(code)}`, { method: "PUT", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ name, base_url: baseUrl, api_key: apiKey || null, models: models.split(",").map(v => v.trim()).filter(Boolean), enabled: true }) });
    const body = await response.json(); if (!response.ok) { setMessage(body.detail || "保存失败"); return; }
    setApiKey(""); setMessage("供应商配置已加密保存"); await load();
  };
  const saveStrategy = async () => { const model = models.split(",")[0].trim(); const response = await fetch("/api/admin/ai/strategy", { method: "PUT", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ planning_provider: code, planning_model: model, execution_provider: code, execution_model: model, summary_provider: code, summary_model: model, temperature: Number(temperature), max_tokens: 8000, timeout_seconds: Number(timeout), max_retries: 2 }) }); setMessage(response.ok ? "模型策略已保存" : "模型策略保存失败"); };
  const enableDataHub = async () => { const response = await fetch("/api/admin/ai/sources/data_hub", { method: "PUT", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ enabled: true, priority: 0, markets: ["A股", "基金", "新闻"] }) }); setMessage(response.ok ? "Data Hub 已设为首选数据源" : "数据源保存失败"); };
  return <div className="mx-auto max-w-6xl space-y-6 p-8"><header><p className="text-xs font-semibold text-primary">AI RUNTIME</p><h1 className="mt-1 text-2xl font-semibold">AI 投研配置</h1><p className="mt-2 text-sm text-muted-foreground">平台统一管理模型、生成参数、密钥和研究数据源；普通用户不可见。</p></header><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div className="space-y-6"><section className="rounded-xl border bg-card p-6"><h2 className="flex items-center gap-2 font-semibold"><KeyRound className="h-4 w-4 text-primary"/>模型供应商</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="供应商代码" value={code} onChange={setCode}/><Field label="显示名称" value={name} onChange={setName}/><Field label="API Base URL" value={baseUrl} onChange={setBaseUrl}/><Field label="模型（逗号分隔）" value={models} onChange={setModels}/><div className="sm:col-span-2"><Field label="API Key（留空则保留原密钥）" value={apiKey} onChange={setApiKey} secret/></div></div><button onClick={() => void save()} className="mt-5 inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground"><Save className="h-4 w-4"/>保存供应商</button></section><section className="rounded-xl border bg-card p-6"><h2 className="font-semibold">模型策略与生成参数</h2><p className="mt-1 text-xs text-muted-foreground">规划、执行和总结默认使用当前供应商的第一个模型。</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Temperature" value={temperature} onChange={setTemperature}/><Field label="超时（秒）" value={timeout} onChange={setTimeoutValue}/></div><div className="mt-5 flex gap-3"><button onClick={() => void saveStrategy()} className="rounded-md border px-4 py-2 text-sm font-medium">保存模型策略</button><button onClick={() => void enableDataHub()} className="rounded-md border px-4 py-2 text-sm font-medium">Data Hub 设为首选源</button></div></section>{message && <p className="text-sm text-muted-foreground">{message}</p>}</div><section className="rounded-xl border bg-card p-5"><h2 className="flex items-center gap-2 font-semibold"><Bot className="h-4 w-4 text-primary"/>已配置供应商</h2><div className="mt-4 space-y-3">{providers.map(item => <div key={item.code} className="rounded-lg border p-3"><div className="flex justify-between text-sm font-medium"><span>{item.name}</span><span className={item.configured ? "text-emerald-600" : "text-amber-600"}>{item.configured ? "已配置" : "缺少密钥"}</span></div><div className="mt-2 text-xs text-muted-foreground">{item.code} · {item.models.join("、") || "未设置模型"}</div><div className="mt-1 text-xs text-muted-foreground">{item.api_key_masked ?? "未设置密钥"}</div></div>)}</div></section></div></div>;
}

function Field({ label, value, onChange, secret = false }: { label: string; value: string; onChange: (value: string) => void; secret?: boolean }) { return <label className="text-sm"><span className="text-xs text-muted-foreground">{label}</span><input type={secret ? "password" : "text"} value={value} onChange={event => onChange(event.target.value)} className="mt-1 h-10 w-full rounded-md border bg-background px-3 outline-none focus:ring-2 focus:ring-primary/20"/></label>; }
