import { useEffect, useMemo, useState } from "react";
import { Bot, CheckCircle2, Database, KeyRound, Plus, RefreshCw, Save, Server, SlidersHorizontal } from "lucide-react";
import { authHeaders } from "@/lib/apiAuth";

type Tab = "connections" | "strategy" | "sources";
type Provider = { code: string; name: string; base_url: string; models: string[]; enabled: boolean; api_key_masked: string | null; configured: boolean };
type Source = { code: string; enabled: boolean; priority: number; markets: string[] };
type Strategy = Record<string, string | number>;
const PRESETS = [
  { code: "openai", name: "OpenAI", base_url: "https://api.openai.com/v1", model: "gpt-5.2" },
  { code: "deepseek", name: "DeepSeek", base_url: "https://api.deepseek.com/v1", model: "deepseek-chat" },
  { code: "qwen", name: "阿里云百炼", base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1", model: "qwen-max" },
  { code: "siliconflow", name: "SiliconFlow", base_url: "https://api.siliconflow.cn/v1", model: "deepseek-ai/DeepSeek-V3" },
];
const SOURCE_META: Record<string, { name: string; detail: string }> = {
  data_hub: { name: "SigmX Data Hub", detail: "平台主数据源，提供标准化行情、财务与情报接口" },
  local_market_store: { name: "本地市场库", detail: "同步后的本地只读数据，作为低延迟缓存和降级源" },
  tushare: { name: "Tushare", detail: "A 股财务与历史数据候补源" },
  public_source: { name: "公开数据源", detail: "仅在主数据源不可用时参与降级" },
};

export function AISettingsPage() {
  const [tab, setTab] = useState<Tab>("connections"); const [providers, setProviders] = useState<Provider[]>([]); const [sources, setSources] = useState<Source[]>([]); const [strategy, setStrategy] = useState<Strategy>({});
  const [editing, setEditing] = useState<Provider | null>(null); const [apiKey, setApiKey] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState("");
  const load = async () => { setLoading(true); setLoadError(""); try { const headers = authHeaders(); const [p, s, m] = await Promise.all([readJson<Provider[]>("/api/admin/ai/providers", headers), readJson<Source[]>("/api/admin/ai/sources", headers), readJson<Strategy>("/api/admin/ai/strategy", headers)]); setProviders(p); setSources(s); setStrategy(m); } catch (cause) { setLoadError(cause instanceof Error ? cause.message : "平台配置加载失败"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const selected = editing ?? providers[0] ?? null;
  return <div className="mx-auto max-w-7xl space-y-6 p-8"><header className="flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-primary">AI Research Runtime</p><h1 className="mt-1 text-2xl font-semibold">AI 投研配置</h1><p className="mt-2 text-sm text-muted-foreground">平台级配置，统一供 Web AI 发现使用，不下放给普通用户。</p></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><RefreshCw className="h-4 w-4"/>刷新</button></header>
    <nav className="flex gap-1 rounded-xl border bg-card p-1">{([{ key: "connections", label: "模型连接", icon: Server }, { key: "strategy", label: "模型策略与生成参数", icon: SlidersHorizontal }, { key: "sources", label: "数据源路由", icon: Database }] as const).map(item => <button key={item.key} onClick={() => setTab(item.key)} className={`flex items-center gap-2 rounded-lg px-4 py-2.5 text-sm ${tab === item.key ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted"}`}><item.icon className="h-4 w-4"/>{item.label}</button>)}</nav>
    {message && <div className="rounded-lg border bg-card px-4 py-3 text-sm">{message}</div>}
    {loading ? <div className="p-20 text-center text-sm text-muted-foreground">正在加载平台配置…</div> : loadError ? <div className="rounded-xl border border-red-200 bg-red-50 p-8 text-center"><p className="text-sm text-red-700">{loadError}</p><button onClick={() => void load()} className="mt-4 rounded-md border border-red-200 bg-white px-3 py-2 text-sm">重新加载</button></div> : tab === "connections" ? <Connections providers={providers} selected={selected} setEditing={setEditing} apiKey={apiKey} setApiKey={setApiKey} onSaved={async text => { setMessage(text); setApiKey(""); await load(); }}/> : tab === "strategy" ? <StrategyPanel providers={providers} value={strategy} onSaved={async text => { setMessage(text); await load(); }}/> : <SourcesPanel sources={sources} onSaved={async text => { setMessage(text); await load(); }}/>
    }
  </div>;
}

async function readJson<T>(url: string, headers: Record<string, string>): Promise<T> { const response = await fetch(url, { headers }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || `平台配置请求失败（${response.status}）`); return body as T; }

function Connections({ providers, selected, setEditing, apiKey, setApiKey, onSaved }: { providers: Provider[]; selected: Provider | null; setEditing: (value: Provider) => void; apiKey: string; setApiKey: (value: string) => void; onSaved: (text: string) => Promise<void> }) {
  const createPreset = (preset = PRESETS[0]) => setEditing({ code: preset.code, name: preset.name, base_url: preset.base_url, models: [preset.model], enabled: true, api_key_masked: null, configured: false });
  return <div className="grid gap-6 lg:grid-cols-[360px_1fr]"><section className="rounded-xl border bg-card"><div className="flex items-center justify-between border-b p-4"><div><h2 className="font-semibold">模型连接</h2><p className="text-xs text-muted-foreground">一个供应商可登记多个模型</p></div><button onClick={() => createPreset()} className="rounded-md border p-2" aria-label="新增模型连接"><Plus className="h-4 w-4"/></button></div><div className="space-y-2 p-3">{providers.map(item => <button key={item.code} onClick={() => setEditing(item)} className={`w-full rounded-lg border p-3 text-left ${selected?.code === item.code ? "border-primary bg-primary/5" : "hover:bg-muted/40"}`}><div className="flex justify-between"><span className="font-medium">{item.name}</span><Status ok={item.configured && item.enabled}/></div><div className="mt-2 text-xs text-muted-foreground">{item.models.length} 个模型 · {item.api_key_masked ?? "未配置密钥"}</div></button>)}{providers.length === 0 && <div className="p-5 text-center text-sm text-muted-foreground"><p>尚未创建模型连接</p><div className="mt-3 flex flex-wrap justify-center gap-2">{PRESETS.map(item => <button key={item.code} onClick={() => createPreset(item)} className="rounded-md border px-2 py-1 text-xs">{item.name}</button>)}</div></div>}</div></section>{selected ? <ConnectionEditor key={selected.code} value={selected} apiKey={apiKey} setApiKey={setApiKey} onSaved={onSaved}/> : <Empty icon={Bot} title="选择或新建模型连接"/>}</div>;
}

function ConnectionEditor({ value, apiKey, setApiKey, onSaved }: { value: Provider; apiKey: string; setApiKey: (v: string) => void; onSaved: (text: string) => Promise<void> }) {
  const [form, setForm] = useState(value); const save = async () => { const response = await fetch(`/api/admin/ai/providers/${encodeURIComponent(form.code)}`, { method: "PUT", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify({ name: form.name, base_url: form.base_url, api_key: apiKey || null, models: form.models, enabled: form.enabled }) }); const body = await response.json(); await onSaved(response.ok ? "模型连接已加密保存" : body.detail || "保存失败"); };
  return <section className="rounded-xl border bg-card p-6"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold">{form.name}</h2><p className="mt-1 text-xs text-muted-foreground">连接标识：{form.code}</p></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={e => setForm({ ...form, enabled: e.target.checked })}/>启用</label></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="连接名称" value={form.name} onChange={name => setForm({ ...form, name })}/><Field label="OpenAI 兼容服务地址" value={form.base_url} onChange={base_url => setForm({ ...form, base_url })}/><div className="sm:col-span-2"><Field label="模型 ID（逗号分隔）" value={form.models.join(", ")} onChange={text => setForm({ ...form, models: text.split(",").map(v => v.trim()).filter(Boolean) })}/></div><div className="sm:col-span-2"><Field secret label="API Key（留空保留原密钥）" value={apiKey} onChange={setApiKey} hint={form.api_key_masked ? `当前：${form.api_key_masked}` : "尚未配置"}/></div></div><button onClick={() => void save()} className="mt-6 inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground"><Save className="h-4 w-4"/>保存模型连接</button></section>;
}

function StrategyPanel({ providers, value, onSaved }: { providers: Provider[]; value: Strategy; onSaved: (text: string) => Promise<void> }) {
  const first = providers.find(item => item.enabled); const defaultModel = first?.models[0] ?? ""; const [form, setForm] = useState({ planning_provider: String(value.planning_provider ?? first?.code ?? ""), planning_model: String(value.planning_model ?? defaultModel), execution_provider: String(value.execution_provider ?? first?.code ?? ""), execution_model: String(value.execution_model ?? defaultModel), summary_provider: String(value.summary_provider ?? first?.code ?? ""), summary_model: String(value.summary_model ?? defaultModel), temperature: Number(value.temperature ?? .2), max_tokens: Number(value.max_tokens ?? 8000), timeout_seconds: Number(value.timeout_seconds ?? 90), max_retries: Number(value.max_retries ?? 2) });
  const save = async () => { const response = await fetch("/api/admin/ai/strategy", { method: "PUT", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify(form) }); const body = await response.json(); await onSaved(response.ok ? "模型策略已保存，新的研究任务将立即生效" : body.detail || "保存失败"); };
  const binding = (stage: "planning" | "execution" | "summary", title: string, detail: string) => <div className="rounded-xl border p-4"><h3 className="font-medium">{title}</h3><p className="mt-1 text-xs text-muted-foreground">{detail}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><select aria-label={`${title}供应商`} value={form[`${stage}_provider`]} onChange={e => { const p = providers.find(x => x.code === e.target.value); setForm({ ...form, [`${stage}_provider`]: e.target.value, [`${stage}_model`]: p?.models[0] ?? "" }); }} className="rounded-md border bg-background px-3 py-2 text-sm">{providers.filter(p => p.enabled).map(p => <option key={p.code} value={p.code}>{p.name}</option>)}</select><input aria-label={`${title}模型`} value={form[`${stage}_model`]} onChange={e => setForm({ ...form, [`${stage}_model`]: e.target.value })} className="rounded-md border bg-background px-3 py-2 text-sm"/></div></div>;
  return <div className="space-y-5"><section className="grid gap-4 lg:grid-cols-3">{binding("planning", "问题规划", "理解意图、拆解指标和检查数据可用性")}{binding("execution", "智能体执行", "调用 Skills 与 Data Hub，形成证据链")}{binding("summary", "报告总结", "组织结论、风险与引用")}</section><section className="rounded-xl border bg-card p-6"><h2 className="font-semibold">生成参数</h2><div className="mt-4 grid gap-4 sm:grid-cols-4"><NumberField label="温度" value={form.temperature} onChange={temperature => setForm({ ...form, temperature })}/><NumberField label="最大输出 Token" value={form.max_tokens} onChange={max_tokens => setForm({ ...form, max_tokens })}/><NumberField label="超时（秒）" value={form.timeout_seconds} onChange={timeout_seconds => setForm({ ...form, timeout_seconds })}/><NumberField label="最大重试" value={form.max_retries} onChange={max_retries => setForm({ ...form, max_retries })}/></div><button onClick={() => void save()} disabled={!providers.length} className="mt-6 inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50"><Save className="h-4 w-4"/>保存并应用策略</button></section></div>;
}

function SourcesPanel({ sources, onSaved }: { sources: Source[]; onSaved: (text: string) => Promise<void> }) {
  const rows = useMemo(() => Object.keys(SOURCE_META).map((code, index) => sources.find(item => item.code === code) ?? { code, enabled: code === "data_hub", priority: index, markets: ["A股"] }), [sources]);
  const save = async (item: Source) => { const response = await fetch(`/api/admin/ai/sources/${item.code}`, { method: "PUT", headers: { "Content-Type": "application/json", ...authHeaders() }, body: JSON.stringify(item) }); const body = await response.json(); await onSaved(response.ok ? `${SOURCE_META[item.code]?.name ?? item.code} 路由已保存` : body.detail || "保存失败"); };
  return <section className="overflow-hidden rounded-xl border bg-card"><div className="border-b p-5"><h2 className="font-semibold">研究数据源路由</h2><p className="mt-1 text-xs text-muted-foreground">按优先级调用；Data Hub 应作为主源，本地库与公共源只负责缓存或降级。</p></div><div className="divide-y">{rows.map(item => <SourceRow key={item.code} value={item} onSave={save}/>)}</div></section>;
}
function SourceRow({ value, onSave }: { value: Source; onSave: (value: Source) => Promise<void> }) { const [item, setItem] = useState(value); const meta = SOURCE_META[item.code] ?? { name: item.code, detail: "平台研究数据源" }; return <div className="grid items-center gap-4 p-5 md:grid-cols-[1fr_120px_180px_90px]"><div><div className="flex items-center gap-2 font-medium">{meta.name}<Status ok={item.enabled}/></div><p className="mt-1 text-xs text-muted-foreground">{meta.detail}</p></div><label className="text-xs text-muted-foreground">优先级<input type="number" value={item.priority} onChange={e => setItem({ ...item, priority: Number(e.target.value) })} className="mt-1 w-full rounded-md border bg-background px-2 py-2 text-sm"/></label><label className="text-xs text-muted-foreground">覆盖市场<input value={item.markets.join("、")} onChange={e => setItem({ ...item, markets: e.target.value.split(/[、,]/).filter(Boolean) })} className="mt-1 w-full rounded-md border bg-background px-2 py-2 text-sm"/></label><div className="space-y-2"><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={item.enabled} onChange={e => setItem({ ...item, enabled: e.target.checked })}/>启用</label><button onClick={() => void onSave(item)} className="rounded-md border px-3 py-1.5 text-xs">保存</button></div></div>; }
function Status({ ok }: { ok: boolean }) { return <span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] ${ok ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{ok && <CheckCircle2 className="h-3 w-3"/>}{ok ? "已启用" : "未就绪"}</span>; }
function Field({ label, value, onChange, secret = false, hint }: { label: string; value: string; onChange: (value: string) => void; secret?: boolean; hint?: string }) { return <label className="block text-sm"><span className="text-xs text-muted-foreground">{label}</span><div className="relative mt-1">{secret && <KeyRound className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/>}<input type={secret ? "password" : "text"} value={value} onChange={e => onChange(e.target.value)} className={`h-10 w-full rounded-md border bg-background px-3 ${secret ? "pl-9" : ""}`}/></div>{hint && <span className="mt-1 block text-xs text-muted-foreground">{hint}</span>}</label>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label className="text-xs text-muted-foreground">{label}<input type="number" value={value} onChange={e => onChange(Number(e.target.value))} className="mt-1 h-10 w-full rounded-md border bg-background px-3 text-sm"/></label>; }
function Empty({ icon: Icon, title }: { icon: typeof Bot; title: string }) { return <div className="grid min-h-80 place-items-center rounded-xl border border-dashed bg-card"><div className="text-center text-sm text-muted-foreground"><Icon className="mx-auto mb-3 h-6 w-6"/>{title}</div></div>; }
