import { useEffect, useMemo, useState } from "react";
import { ArrowRight, ExternalLink, Globe2, Landmark, LoaderCircle, Search, ShieldCheck, Sparkles, TrendingUp, X } from "lucide-react";
import { useNavigate } from "react-router-dom";

interface EventItem { id: string; title: string; summary: string; event_type: string; status: string; importance: number; confidence: number; region: string; first_seen_at: string; updated_at: string; evidence_count: number }
interface EventDetail extends EventItem { evidence: Array<{ id: string; title: string; url: string; source: string; published_at: string; is_key: boolean }> }
const categories = [["", "全部"], ["macro_policy", "宏观"], ["geopolitical", "政策"], ["company", "公司"], ["energy_commodity", "市场"]] as const;

export function GlobalEventsPage() {
  const navigate = useNavigate();
  const [category, setCategory] = useState("");
  const [query, setQuery] = useState("");
  const [visibleCount, setVisibleCount] = useState(8);
  const [items, setItems] = useState<EventItem[]>([]);
  const [selected, setSelected] = useState<EventDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { setLoading(true); setError(""); fetch(`/api/public/global-events?event_type=${encodeURIComponent(category)}&limit=60`).then(r => { if (!r.ok) throw new Error(`全球事件请求失败（${r.status}）`); return r.json(); }).then(data => setItems(data.items ?? [])).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [category]);
  const visible = useMemo(() => items.filter(item => `${item.title} ${item.summary} ${item.region}`.toLowerCase().includes(query.trim().toLowerCase())), [items, query]);
  const open = async (item: EventItem) => { const response = await fetch(`/api/public/global-events/${item.id}`); if (response.ok) setSelected(await response.json()); };
  const research = (item: EventItem) => navigate(`/?q=${encodeURIComponent(`分析全球事件“${item.title}”对 A 股、港股及相关行业的影响，并核验其证据`)}`);

  return <div className="bg-white text-zinc-950"><main className="mx-auto max-w-[1440px] px-5 py-6 sm:px-8 lg:px-10 lg:py-7">
    <header className="flex flex-col gap-4 border-b border-zinc-100 pb-5 md:flex-row md:items-center md:justify-between"><div><h1 className="text-[24px] font-semibold tracking-[-0.035em]">全球事件</h1><p className="mt-1 text-[13px] text-zinc-500">追踪影响市场的重要变化</p></div><label className="relative block w-full md:w-[360px]"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-400"/><input aria-label="搜索全球事件" value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索事件、主题或地区" className="h-10 w-full rounded-xl border border-zinc-200 bg-zinc-50/50 pl-10 pr-3 text-[13px] outline-none transition focus:border-zinc-400 focus:bg-white focus:ring-4 focus:ring-zinc-100"/></label></header>
    <div className="mt-4 flex gap-2 overflow-x-auto">{categories.map(([id, label]) => <button key={id} onClick={() => setCategory(id)} className={`shrink-0 rounded-lg border px-3.5 py-2 text-[12px] transition ${category === id ? "border-zinc-950 bg-zinc-950 text-white" : "border-zinc-200 text-zinc-600 hover:border-zinc-300 hover:bg-zinc-50"}`}>{label}</button>)}</div>
    {loading && <div className="flex justify-center gap-2 py-24 text-sm text-zinc-500"><LoaderCircle className="h-5 w-5 animate-spin"/>正在汇总全球事件</div>}
    {error && <div className="mt-6 rounded-xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{error}</div>}
    {!loading && !error && visible.length === 0 && <div className="mt-6 rounded-xl border border-dashed border-zinc-200 py-20 text-center text-sm text-zinc-500">{query ? "没有匹配的全球事件" : "当前没有具备可追溯证据的事件"}</div>}
    {!loading && !error && visible.length > 0 && <div className="mt-6 grid gap-5 xl:grid-cols-[minmax(0,1fr)_286px]"><section><h2 className="mb-3 text-[15px] font-semibold">今天</h2><div className="relative ml-2 border-l border-zinc-200 pl-5">{visible.slice(0, visibleCount).map((item, index) => <EventRow key={item.id} item={item} featured={index === 0} onOpen={open} onResearch={research}/>)}</div>{visibleCount < visible.length && <div className="mt-5 flex justify-center"><button type="button" onClick={() => setVisibleCount(count => count + 8)} className="rounded-xl border border-zinc-300 px-5 py-2.5 text-[13px] font-medium text-zinc-700 hover:bg-zinc-50">加载更多事件</button></div>}</section><ImpactPanel items={visible}/></div>}
  </main>{selected && <div className="fixed inset-0 z-50 flex justify-end bg-zinc-950/30" onMouseDown={() => setSelected(null)}><aside role="dialog" aria-label="事件详情" className="h-full w-full max-w-2xl overflow-y-auto bg-white shadow-2xl" onMouseDown={event => event.stopPropagation()}><div className="flex items-start justify-between border-b border-zinc-200 p-6"><div><div className="text-xs font-medium text-zinc-500">事件证据与演化</div><h2 className="mt-2 text-xl font-semibold">{selected.title}</h2></div><button onClick={() => setSelected(null)} aria-label="关闭"><X className="h-5 w-5"/></button></div><div className="p-6"><p className="text-sm leading-7 text-zinc-600">{selected.summary}</p><h3 className="mt-7 font-semibold">支撑证据</h3><div className="mt-3 divide-y divide-zinc-200 rounded-xl border border-zinc-200">{selected.evidence.map(evidence => <a key={evidence.id} href={evidence.url} target="_blank" rel="noreferrer" className="block p-4 hover:bg-zinc-50"><div className="font-medium">{evidence.title}</div><div className="mt-2 flex items-center gap-2 text-xs text-zinc-500">{evidence.source} · {new Date(evidence.published_at).toLocaleString()} <ExternalLink className="h-3.5 w-3.5"/></div></a>)}</div><button onClick={() => research(selected)} className="mt-6 w-full rounded-xl bg-zinc-950 py-3 text-sm font-semibold text-white">基于事件与证据运行 AI 研究</button></div></aside></div>}</div>;
}

function EventRow({ item, featured, onOpen, onResearch }: { item: EventItem; featured: boolean; onOpen: (item: EventItem) => void; onResearch: (item: EventItem) => void }) {
  const time = new Date(item.updated_at).toLocaleTimeString("zh-CN", { hour: "2-digit", minute: "2-digit" });
  return <article className="relative border-b border-zinc-200 py-5 first:pt-2"><span className="absolute -left-[25px] top-7 h-2 w-2 rounded-full border-2 border-white bg-zinc-400 ring-1 ring-zinc-300"/><div className="grid gap-3 sm:grid-cols-[72px_minmax(0,1fr)]"><div className="text-[12px] text-zinc-500"><div className="font-medium text-zinc-700">{time}</div><div className="mt-1">北京时间</div></div><div><div className="flex items-start gap-2"><span className="mt-0.5 rounded-md bg-blue-50 px-2 py-1 text-[11px] font-medium text-blue-700">{item.region || "全球"}</span><div className="min-w-0 flex-1"><h3 className="line-clamp-2 text-[15px] font-semibold leading-6 tracking-[-0.01em]">{item.title}</h3><p className="mt-1 line-clamp-2 text-[13px] leading-6 text-zinc-500">{item.summary}</p></div></div><div className="mt-3 flex flex-wrap items-center gap-2 text-[12px]"><span className="text-zinc-500">影响资产</span><span className="rounded-full border border-zinc-200 px-2 py-1 text-zinc-500">A股</span><span className="rounded-full border border-zinc-200 px-2 py-1 text-zinc-500">港股</span><span className="rounded-full border border-zinc-200 px-2 py-1 text-zinc-500">大宗商品</span><button type="button" onClick={() => onResearch(item)} aria-label={`让 AI 分析影响 ${item.title}`} className="ml-auto inline-flex items-center gap-1 font-medium text-blue-600 hover:text-blue-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500/40">让 AI 分析影响 <ArrowRight className="h-3.5 w-3.5"/></button></div>{featured && <div className="mt-4 rounded-xl border border-zinc-200 bg-zinc-50/70 p-4"><div className="flex items-center gap-2 text-[12px] font-semibold"><Sparkles className="h-4 w-4"/>AI 分析摘要</div><p className="mt-2 text-[13px] leading-5 text-zinc-600">该事件可能改变利率、风险偏好与行业估值预期，建议结合后续数据与政策表态持续核验。</p><button onClick={() => void onOpen(item)} className="mt-3 inline-flex items-center gap-1 text-[12px] font-medium text-zinc-600 hover:text-zinc-950"><ShieldCheck className="h-3.5 w-3.5"/>{item.evidence_count} 条可追溯证据 · 展开详情</button></div>}</div></div></article>;
}

function ImpactPanel({ items }: { items: EventItem[] }) { return <aside className="h-fit rounded-2xl border border-zinc-200 p-5 xl:sticky xl:top-20"><h2 className="text-[16px] font-semibold">市场影响</h2><div className="mt-4 divide-y divide-zinc-200"><Impact icon={TrendingUp} title="利率与货币" text="政策预期变化正在影响债券收益率与成长资产估值。"/><Impact icon={Globe2} title="风险情绪" text="全球市场风险偏好随事件演化保持波动。"/><Impact icon={Landmark} title="重点关注" text={`${items.length} 个事件仍在持续更新，建议核验新增证据。`}/></div><p className="mt-5 text-[10px] text-zinc-400">内容基于当前事件聚合，仅供研究参考</p></aside>; }
function Impact({ icon: Icon, title, text }: { icon: typeof Globe2; title: string; text: string }) { return <div className="py-4 first:pt-0"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-emerald-50 text-emerald-700"><Icon className="h-4 w-4"/></span><h3 className="text-[13px] font-semibold">{title}</h3></div><p className="mt-2 pl-10 text-[12px] leading-5 text-zinc-500">{text}</p></div>; }
