import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, CheckCircle2, LoaderCircle, Search, Sparkles } from "lucide-react";
import { getSkills, type PublicSkill } from "@/lib/skillsApi";

export function ResearchSkillsPage() {
  const [skills, setSkills] = useState<PublicSkill[]>([]); const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { getSkills().then(setSkills).catch(cause => setError(cause instanceof Error ? cause.message : "技能目录不可用")).finally(() => setLoading(false)); }, []);
  const filtered = useMemo(() => skills.filter(skill => `${skill.name} ${skill.description} ${skill.slug}`.toLowerCase().includes(query.trim().toLowerCase())), [skills, query]);
  return <div className="min-h-screen bg-slate-50 text-slate-950"><section className="border-b bg-white"><div className="mx-auto max-w-7xl px-6 py-8"><div className="flex items-center gap-2 text-xs font-bold text-primary"><Sparkles className="h-4 w-4"/> SIGMX RESEARCH SKILLS</div><h1 className="mt-2 text-3xl font-bold">AI 投研技能库</h1><p className="mt-3 text-sm text-slate-500">直接安装到本地 AI 智能体；目录内容来自服务端已发布的 SKILL.md。</p></div></section><main className="mx-auto max-w-7xl px-6 py-7"><label className="relative block rounded-xl border bg-white p-4 shadow-sm"><Search className="absolute left-7 top-7 h-4 w-4 text-slate-400"/><input aria-label="搜索投研 Skills" value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索技能或研究场景" className="h-10 w-full rounded-lg border bg-slate-50 pl-9 pr-3 text-sm outline-none"/></label>{loading && <div className="flex justify-center gap-2 py-20 text-sm text-slate-500"><LoaderCircle className="h-5 w-5 animate-spin"/>正在读取技能目录</div>}{error && <div className="mt-6 rounded-lg bg-red-50 p-4 text-sm text-red-700">{error}</div>}{!loading && !error && <section className="mt-8"><div className="flex justify-between"><h2 className="text-lg font-bold">全部 Skills</h2><span className="text-xs text-slate-400">{filtered.length} 个已发布技能</span></div><div data-testid="research-skills-grid" className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{filtered.map(skill => <Link data-testid="research-skill-card" key={skill.slug} to={`/skills/${skill.slug}`} aria-label={`${skill.name} 查看详情`} className="group flex min-h-56 flex-col rounded-xl border bg-white p-5 hover:border-primary/40 hover:shadow-md"><div className="flex justify-between"><code className="text-[11px] text-primary">{skill.slug}</code>{skill.official && <span className="inline-flex items-center gap-1 text-[11px] text-slate-400"><CheckCircle2 className="h-3.5 w-3.5 text-primary"/>官方</span>}</div><h3 className="mt-4 font-bold group-hover:text-primary">{skill.name}</h3><p className="mt-2 line-clamp-4 text-sm leading-6 text-slate-500">{skill.description || "请进入详情查看技能说明。"}</p><div className="mt-auto flex justify-end border-t pt-4 text-xs font-semibold text-primary">安装使用 <ArrowRight className="ml-1 h-3.5 w-3.5"/></div></Link>)}</div>{filtered.length === 0 && <div className="mt-4 rounded-xl border border-dashed py-16 text-center text-sm text-slate-500">没有匹配的已发布 Skill</div>}</section>}</main></div>;
}
