import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, Bot, Check, Copy, LoaderCircle, Terminal } from "lucide-react";
import { getSkill, type PublicSkillDetail } from "@/lib/skillsApi";

export function ResearchSkillDetailPage() {
  const { slug = "" } = useParams(); const [skill, setSkill] = useState<PublicSkillDetail | null>(null); const [error, setError] = useState(""); const [mode, setMode] = useState<"agent" | "cli">("agent"); const [copied, setCopied] = useState(false);
  useEffect(() => { getSkill(slug).then(setSkill).catch(cause => setError(cause instanceof Error ? cause.message : "Skill 不存在")); }, [slug]);
  if (error) return <State text={error}/>; if (!skill) return <State text="正在读取已发布 Skill" loading/>;
  const command = `sigmx skills install ${skill.slug}`;
  const prompt = `请在我的本地环境安装 SigmX Skill「${skill.slug}」。先检查是否已安装 SigmX Skills CLI；如未安装，请阅读 https://skills.sigmx.cn/install.sh 并仅安装 CLI。随后运行「${command}」。请确认本地环境已设置 SIGMX_DATA_HUB_BASE_URL 和 SIGMX_DATA_HUB_KEY，不要在对话中回显完整密钥。安装后验证当前 AI 助手可以发现该 Skill。`;
  const copy = async () => { await navigator.clipboard?.writeText(mode === "agent" ? prompt : command); setCopied(true); };
  return <div className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto max-w-6xl px-6 py-7"><Link to="/skills" className="inline-flex items-center gap-1 text-xs font-semibold text-slate-500"><ArrowLeft className="h-3.5 w-3.5"/>返回技能库</Link><div className="mt-5 text-xs font-semibold text-primary">{skill.official ? "SIGMX 官方" : "社区"}</div><h1 className="mt-2 text-3xl font-bold">{skill.name}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-500">{skill.description}</p><div className="mt-3 text-xs text-slate-400">清单更新时间 {new Date(skill.updated_at).toLocaleString()}</div></div></header><main className="mx-auto grid max-w-6xl gap-6 px-6 py-7 lg:grid-cols-[1fr_380px]"><section><h2 className="font-bold">SKILL.md</h2><pre className="mt-3 max-h-[70vh] overflow-auto whitespace-pre-wrap rounded-xl bg-slate-950 p-5 text-xs leading-6 text-slate-200">{skill.content}</pre></section><aside className="h-fit rounded-2xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 font-bold"><Bot className="h-5 w-5 text-primary"/>安装 Skill</h2><div className="mt-5 grid grid-cols-2 rounded-xl bg-slate-100 p-1"><button aria-pressed={mode === "agent"} onClick={() => {setMode("agent");setCopied(false);}} className={`rounded-lg py-2 text-xs font-semibold ${mode === "agent" ? "bg-white text-primary shadow-sm" : "text-slate-500"}`}><Bot className="mr-1 inline h-3.5 w-3.5"/>AI 助手</button><button aria-pressed={mode === "cli"} onClick={() => {setMode("cli");setCopied(false);}} className={`rounded-lg py-2 text-xs font-semibold ${mode === "cli" ? "bg-white text-primary shadow-sm" : "text-slate-500"}`}><Terminal className="mr-1 inline h-3.5 w-3.5"/>CLI</button></div><pre data-testid={mode === "agent" ? "agent-install-prompt" : "install-command"} className="mt-4 max-h-72 overflow-auto whitespace-pre-wrap rounded-xl bg-slate-950 p-4 text-xs leading-6 text-slate-200">{mode === "agent" ? prompt : command}</pre><button onClick={() => void copy()} className="mt-3 flex w-full items-center justify-center gap-2 rounded-lg bg-primary py-2.5 text-sm font-semibold text-white">{copied ? <Check className="h-4 w-4"/> : <Copy className="h-4 w-4"/>}{copied ? "已复制" : "复制安装内容"}</button><p className="mt-4 text-xs leading-5 text-slate-500">安装后由本地智能体执行；Data Hub Credential 仅保存在用户本地环境。</p></aside></main></div>;
}
function State({ text, loading = false }: { text: string; loading?: boolean }) { return <div className="grid min-h-[70vh] place-items-center bg-slate-50 text-center">{loading && <LoaderCircle className="mx-auto h-6 w-6 animate-spin text-primary"/>}<div className="mt-3 font-semibold">{text}</div><Link to="/skills" className="mt-4 inline-block text-sm text-primary">返回技能库</Link></div>; }
